Budget features
DianaBeki/budget-app pull request #2
Opened 2023-10-27 16:03 UTC by DianaBeki

### Project requirements
[Day 1](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#day-1)

-  Set up the repository and tools.
- Create your models according to the ERD diagram. Don't forget about validations and tests.
- Implement the authentication and authorization.

[Day 2](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#day-2)

- Create the page to add a category.
- Create the home page.
- Create the page to add a transaction.
- Create the transactions page.

[Day 3](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#day-3)

- Make sure your app is tested adequately.
- Deploy the project, and test for final details.
- Record a video for your project.
- Create a good README and PR description

2023-10-27 19:06 UTC, OLIPLICHE requested changes
Hi @DianaBeki, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Build a mobile web application 👍 
- Able to make a list of transactions associated with a category 👍
-  The user can log in to the app using email and password 👍 
- Use Postgres as the database 👍 
- use devise for authentication 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 19:06 UTC, OLIPLICHE commented on spec/models/category_spec.rb
> +  end
- [ ] Hello, nice job so far. I suggest you work on the Testing again because the test did not pass.

![Capture](https://github.com/DianaBeki/budget-app/assets/63972670/4a702a28-7c0e-4515-b0eb-e0f7d27be887)

2023-10-27 19:18 UTC, DianaBeki commented on spec/models/category_spec.rb
> +  end
@OLIPLICHE seen the changes but on my terminal I made sure the tests were passing for me to be able to submit and here is the evidence cos I did it  again now .Kindly confirm in your side .Thank you
![spec](https://github.com/DianaBeki/budget-app/assets/99320947/0e8fe075-49be-48ff-80af-bff3d881e79c)

2023-10-27 19:36 UTC, OLIPLICHE commented
- [ ]  Hi, **This is for the second reviewer**, I met @DianaBeki on Slack who just showed me that the test on Categorie file has passed at her end. I humbly asked the second reviewer to check it again and confirm and approve the project if it works. Thank you.

2023-10-28 08:30 UTC, prolajumokeoni approved these changes
Hi @DianaBeki 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Resolved requested change with reviewer ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 08:47 UTC, merged